package:  page_counter
version:  '1.4'
author:   Wolfgang Busch
supportpage: redaxo.org/support/community/

page:
    title: 'translate:page_counter'
    perm:  admin[]
    icon:  rex-icon fa-bar-chart
    subpages:
        introduction: { title: 'translate:introduction' }
        description:  { title: 'translate:description' }
        handling:     { title: 'translate:handling' }
        hitlist:      { title: 'translate:hitlist' }

requires:
    redaxo: ^5.3.0
